version: '3.7'

services:
  db:
    image: mysql:8
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    environment:
      - MYSQL_ROOT_PASSWORD=invoices
      - MYSQL_DATABASE=invoices
    restart: always
    ports:
      - "3339:3306"
    volumes:
      - "./database/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql"
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD -e \"SELECT 1\" $$MYSQL_DATABASE &> /dev/null" ]
      interval: 30s
      timeout: 30s
      retries: 3
